<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Version>1.0.3</Version>
		<StartupObject>KerioTrafficMonitor.App</StartupObject>
		<ApplicationIcon>Assets\KerioTrafficMonitor.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\KerioTrafficMonitor.ico" />
	</ItemGroup>


	<ItemGroup>
		<ApplicationDefinition Remove="App.xaml" />
		<Page Include="App.xaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.20" />
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.20" />
		<PackageReference Include="Velopack" Version="1.2.161" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\KerioTrafficMonitor.ico" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
